routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/primeiroacesso', 'HomeController@primeiroacesso')->name('primeiroacesso')->middleware('auth');
Route::post('/primeiroacesso', 'HomeController@update')->name('primeiroacesso.update')->middleware('auth');

// ROTAS AUTENTICADAS
Route::middleware(['auth','primeiroacesso'])->group(function () {

    Route::redirect('/', '/home');
    Route::get('/home', 'HomeController@index')->name('home');

    //Usuários
    Route::resource('usuario', 'UserController');

    //Comorbidade
    Route::resource('comorbidade', 'ComorbidadeController');
    Route::get('/comorbidade/remove/{id}', 'ComorbidadeController@delete');

    //Cargos
    Route::resource('cargo', 'CargoController');
    Route::get('/cargo/remove/{id}', 'CargoController@delete');

    //Tipo de serviço
    Route::resource('tipoServico', 'TipoServicoController');
    Route::get('/tipo-servico/remove/{id}', 'TipoServicoController@delete');

    //Unidades de Saúde
    Route::resource('unidadesaude', 'UnidadeSaudeController');
    Route::get('/unidadesaude/remove/{id}', 'UnidadeSaudeController@delete');

    //Pacientes
    Route::resource('paciente', 'PacienteController');
    Route::get('visualizacao/{paciente}','PacienteController@visualizacao')->name('visualizacao');

    //Vínculo
    Route::resource('vinculo', 'VinculoController');
    Route::get('/vinculo/remove/{id}', 'VinculoController@delete');


});

app/Cargo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cargo extends Model
{
    //
}

app/Http/Controllers/CargoController.php
<?php

namespace App\Http\Controllers;

use App\Cargo;
use Illuminate\Http\Request;
use Request as rq;

class CargoController extends Controller
{
    public function __construct(){
        $this->middleware('verificaperfil:cargos');
    }
    public function index(){

        $cargo = Cargo::orderBy('descricao')->get();

        return view('cargo.index', compact('cargo'));
    }

    public function create(){

        $cargo = new Cargo();

        return view('cargo.formulario', compact('cargo'));
    }

    public function store(Request $request){

        $cargo = new Cargo();
        $cargo->descricao = $request->descricao;

        try {
            $save = $cargo->save();

            if($save){
                rq::session()->flash('status', 'Cargo cadastrado com sucesso.');
            }else{
                rq::session()->flash('status-not', 'Ocorreu um erro ao salvar cargo.');
            }

        }catch (\Exception $e){
            rq::session()->flash('status-not', 'Ocorreu um erro ao salvar cargo.'.$e->getMessage());
        }

        return redirect()->route('cargo.index');
    }

    public function edit(Cargo $cargo){

        return view('cargo.formulario', compact('cargo'));
    }

    public function update(Request $request, Cargo $cargo){

        $cargo->descricao = $request->descricao;

        try {
            $save = $cargo->save();

            if($save){
                rq::session()->flash('status', 'Cargo atualizado com sucesso.');
            }else{
                rq::session()->flash('status-not', 'Ocorreu um erro ao salvar cargo.');
            }

        }catch (\Exception $e){
            rq::session()->flash('status-not', 'Ocorreu um erro ao salvar cargo.'.$e->getMessage());
        }

        return redirect()->route('cargo.index');
    }

    public function delete($id)
    {
        $cargo = Cargo::findOrFail($id);

        try{
            $cargo->delete();
            rq::session()->flash('status', 'Cargo '.$cargo->descricao.' excluído com sucesso.');
            return redirect()->route('cargo.index');
        }
        catch (\Exception $e){

            if($e->getCode() == 23000 ){
                rq::session()->flash('status-not', 'Cargo não foi excluído. O mesma está sendo utilizado em outro cadastro! ');
            }else{
                rq::session()->flash('status-not', 'Cargo não foi excluído! '.$e->getMessage());
            }

            return redirect()->route('cargo.index');
        }

    }
}

resources/views/cargo/formulario.blade.php
@extends('layouts.template')

@section('content')


@include('messages.alert')

@if($cargo->exists)

<div class="col-12 text-center">
    <h3>EDITAR CARGO</h3>
</div>

<form action="{{route('cargo.update', $cargo)}}" method="post">
    <input type="hidden" name="_method" value="put">

    @else

    <div class="col-12 text-center">
        <h3>CADASTRO DE CARGO</h3>
    </div>

    <form action="{{route('cargo.store')}}" method="post">
        @endif
        {{ csrf_field() }}
        <div class="row">
            <div class="form-group col-12">
                <label>Nome *</label>
                <input name="descricao" id="descricao" value="{{old('descricao',$cargo->descricao)}}" type="text" class="form-control" placeholder="Digite o nome do cargo" required />
            </div>
        </div>

        <div class="row">
            <div class="form-group form-footer col-12 text-center" style="margin-bottom: 50px">

                <button class="btn btn-primary" type="submit">Salvar</button>

                <a class="btn btn-default" href="{{route('cargo.index')}}">
                    Cancelar
                </a>
            </div>
        </div>

    </form>
    @endsection

resources/views/cargo/index.blade.php
@extends('layouts.template')

@section('content')

@include('messages.alert')

<div class="text-center col-12 mt-5">
    <a href="{{route('cargo.create')}}" class="btn btn-primary btn-small">
        <b>Novo Cargo</b>
    </a>
</div>

<div class="col-12 text-center mt-3">
    <h1>
        Listagem de Cargos
    </h1>
</div>
<table class="table table-bordered shadow col-12" id="cargoTable">
    <thead>
        <tr class="text-center">
            <th>Nome</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($cargo as $c)
        <tr class="text-center">
            <td>{{$c->descricao}}</td>

            <th>
                <div class="dropdown open">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="triggerId" data-toggle="dropdown">
                        Selecione
                    </button>
                    <div class="dropdown-menu" aria-labelledby="triggerId">
                        <a class="dropdown-item" href="{{route('cargo.edit', $c)}}">Editar</a>
                        <a class="dropdown-item" onclick="return confirm('Confirmar exclusão')" href="{{url('cargo/remove/'.$c->id)}}">Excluir</a>
                    </div>

                </div>
            </th>
        </tr>
        @endforeach
    </tbody>
</table>
</div>

<script>
    $('#cargoTable').DataTable({
        "searching": true,
        "language": {
            "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json"
        },
        "columnDefs": [{
            "targets": [-1],
            "orderable": false
        },
        ],
    });
</script>
@endsection