routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/primeiroacesso', 'HomeController@primeiroacesso')->name('primeiroacesso')->middleware('auth');
Route::post('/primeiroacesso', 'HomeController@update')->name('primeiroacesso.update')->middleware('auth');

// ROTAS AUTENTICADAS
Route::middleware(['auth','primeiroacesso'])->group(function () {

    Route::redirect('/', '/home');
    Route::get('/home', 'HomeController@index')->name('home');

    //Usuários
    Route::resource('usuario', 'UserController');

    //Comorbidade
    Route::resource('comorbidade', 'ComorbidadeController');
    Route::get('/comorbidade/remove/{id}', 'ComorbidadeController@delete');

    //Cargos
    Route::resource('cargo', 'CargoController');
    Route::get('/cargo/remove/{id}', 'CargoController@delete');

    //Tipo de serviço
    Route::resource('tipoServico', 'TipoServicoController');
    Route::get('/tipo-servico/remove/{id}', 'TipoServicoController@delete');

    //Unidades de Saúde
    Route::resource('unidadesaude', 'UnidadeSaudeController');
    Route::get('/unidadesaude/remove/{id}', 'UnidadeSaudeController@delete');

    //Pacientes
    Route::resource('paciente', 'PacienteController');
    Route::get('visualizacao/{paciente}','PacienteController@visualizacao')->name('visualizacao');

    //Vínculo
    Route::resource('vinculo', 'VinculoController');
    Route::get('/vinculo/remove/{id}', 'VinculoController@delete');


});

app/UnidadeSaude.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UnidadeSaude extends Model
{
    protected $table = 'unidades';

    protected $fillable = [
        'nome', 'cnes', 'tipo_prestacao_id','tipo_servico_id',
        'referencia_covid','municipio_id'
    ];

    public function municipio(){
        return $this->belongsTo('App\Municipio');
    }
}

app/Http/Controllers/UnidadeSaudeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreUnidade;
use App\Municipio;
use App\TipoPrestacao;
use App\TipoServico;
use App\UnidadeSaude;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Validator;
use Request as rq;
use Illuminate\Support\Facades\DB;

class UnidadeSaudeController extends Controller
{
    public function __construct(){
        $this->middleware('verificaperfil:unidades');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $unidadesaude = UnidadeSaude::orderBy('nome')->get();

        return view('unidadesaude.index', compact('unidadesaude'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $unidadesaude = new UnidadeSaude();
        $tipo_prestacao = TipoPrestacao::orderBy('descricao')->get();
        $tipo_servico = TipoServico::orderBy('descricao')->get();
        $municipio_id = Municipio::where('estado_id', 3)->get();
        return view('unidadesaude.formulario', compact('unidadesaude','tipo_prestacao','tipo_servico','municipio_id'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUnidade $request)
    {
        $unidadesaude = new UnidadeSaude();
        $unidadesaude->nome = $request->nome;
        $unidadesaude->cnes = $request->cnes;
        $unidadesaude->referencia_covid = $request->referencia_covid;
        $unidadesaude->tipo_prestacao_id = $request->tipo_prestacao_id;
        $unidadesaude->tipo_servico_id = $request->tipo_servico_id;
        $unidadesaude->municipio_id = $request->municipio_id;
        
                
            try{
                $save = $unidadesaude->save();
                if($save){
                    rq::session()->flash('status','Unidade cadastrada com sucesso');
                }else{
                    rq::session()->flash('status-not', 'Ocorreu um erro ao salvar a unidade');
                }
            }catch(\Exception $e){
                rq::session()->flash('status-not','Ocorreu um erro ao salvar a unidade'.$e->getMessage());
            }
            Log::channel('relatoria')->info("Unidade Cadastrada",[
                'user_id'=>auth()->user()->id,
                'dados'=>$unidadesaude
            ]);
            return redirect()->route('unidadesaude.index');
    }
        
        
        // $unidadesaude = Unidadesaude::create([
        //     'nome' => $request->nome,
        //     'cnes' => $request->cnes,
        //     'referencia_covid' => $request->referencia_covid,
        //     'tipo_prestacao_id' => $request->tipo_prestacao_id,
        //     'tipo_servico_id' => $request->tipo_servico_id,
        //     'municipio_id' => $request->municipio_id
        // ]);
        //validacao request
    

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(UnidadeSaude $unidadesaude)
    {
        $tipo_prestacao = TipoPrestacao::orderBy('descricao')->get();
        $tipo_servico = TipoServico::orderBy('descricao')->get();
        $municipio_id = Municipio::where('estado_id', 3)->get();
        return view('unidadesaude.formulario', compact('unidadesaude','tipo_prestacao','tipo_servico','municipio_id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, UnidadeSaude $unidadesaude)
    {
        $unidadesaude->nome = $request->nome;
        $unidadesaude->cnes = $request->cnes;
        $unidadesaude->referencia_covid = $request->referencia_covid;
        $unidadesaude->tipo_prestacao_id = $request->tipo_prestacao_id;
        $unidadesaude->tipo_servico_id = $request->tipo_servico_id;
        $unidadesaude->municipio_id = $request->municipio_id;

        $existeCNES = DB::table('unidades')->where([           
            ['cnes', '=', $unidadesaude->cnes],
            ['id', '<>', $unidadesaude->id],
        ])->count();

        if($existeCNES > 0){        
            rq::session()->flash('status-not', 'Já existe unidade com CNES cadastrado.');
            return redirect()->route('unidadesaude.index');
        }


        try {
            $save = $unidadesaude->save();

            if($save){
                rq::session()->flash('status', 'Unidade atualizada com sucesso.');
            }else{
                rq::session()->flash('status-not', 'Ocorreu um erro ao salvar unidade.');
            }

        }catch (\Exception $e){
            rq::session()->flash('status-not', 'Ocorreu um erro ao salvar unidade.'.$e->getMessage());
        }
        Log::channel('relatoria')->info("Unidade Alterada",[
            'user_id'=>auth()->user()->id,
            'dados'=>$unidadesaude
        ]);
        return redirect()->route('unidadesaude.index');
    }
    

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete($id)
    {
        $unidadesaude = UnidadeSaude::findOrFail($id);
        $unidadesaude->delete();
    }
}

resources/views/unidadesaude/formulario.blade.php
@extends('layouts.template')

@section('content')

@include('messages.alert')


@if($unidadesaude->exists)

<div class="col-12 text-center">
  <h3>EDITAR UNIDADE DE SAÚDE</h3>
</div>

<form action="{{route('unidadesaude.update', $unidadesaude)}}" method="post">
  <input type="hidden" name="_method" value="put">

  @else

  <div class="col-12 text-center">
    <h3>CADASTRO DE UNIDADE DE SAÚDE</h3>
  </div>
 
  @if ($errors->any())
  <div class="alert alert-danger">
    <ul>
      @foreach($errors->all() as $error)
      <li>{{$error}}</li>
      @endforeach
    </ul>
  </div>
  @endif

  <form action="{{route('unidadesaude.store')}}" method="post">
    @endif
    {{ csrf_field() }}
    <div class="row">
      <div class="form-group col-6">
        <label>Nome *</label>
        <input name="nome" id="nome" value="{{old('descricao',$unidadesaude->nome)}}" type="text" class="form-control" placeholder="Digite o nome da unidade de saúde" required />
      </div>
      <div class="form-group col-6">
        <label>CNES *</label>
        <input name="cnes" id="cnes" value="{{old('cnes',$unidadesaude->cnes)}}" type="text" class="form-control" placeholder="Digite o código cnes" required />
      </div>
      <div class="form-group col-6">
        <label>Tipo de Prestação *</label>
        <select class="form-control mb-3" name="tipo_prestacao_id" id="tipo_prestacao_id" required>
          <option value="" selected>-- Selecione --</option>
          @foreach ($tipo_prestacao as $tp)
          <option value="{{$tp->id}}" {{$tp->id == $unidadesaude->tipo_prestacao_id?"selected":""}}>{{$tp->descricao}}</option>
          @endforeach
        </select>
      </div>
      <div class="form-group col-6">
        <label>Tipo de Serviço *</label>
        <select class="form-control mb-3" name="tipo_servico_id" id="tipo_servico_id" required>
          <option value="" selected>-- Selecione --</option>
          @foreach ($tipo_servico as $ts)
          <option value="{{$ts->id}}" {{$ts->id == $unidadesaude->tipo_servico_id?"selected":""}}>
            {{$ts->descricao}}
          </option>
          @endforeach
        </select>
      </div>
      <div class="form-group col-6">
        <label>Referência Covid *</label>
        <select class="form-control mb-3" name="referencia_covid" id="referencia_covid" required>
          <option value="" selected>-- Selecione --</option>
          <option value="1" {{(old('referencia_covid', $unidadesaude->referencia_covid) == '1'?'selected':'')}}>Sim</option>
          <option value="2" {{(old('referencia_covid', $unidadesaude->referencia_covid) == '2'?'selected':'')}}>Não</option>
        </select>
      </div>
      <div class="form-group col-6">
        <label>Município *</label>
        <select class="form-control mb-3" name="municipio_id" id="municipio_id" required>
          <option value="" selected>-- Selecione --</option>
          @foreach ($municipio_id as $mi)
          <option value="{{$mi->id}}" {{$mi->id == $unidadesaude->municipio_id?"selected":""}}>{{$mi->nome}}</option>
          @endforeach
        </select>
      </div>
    </div>

    <div class="row">
      <div class="form-group form-footer col-12 text-center" style="margin-bottom: 50px">

        <button class="btn btn-primary" type="submit">Salvar</button>

        <a class="btn btn-default" href="{{route('unidadesaude.index')}}">
          Cancelar
        </a>
      </div>
    </div>

  </form>
  @endsection

resources/views/unidadesaude/index.blade.php
@extends('layouts.template')

@section('content')

@include('messages.alert')

<div class="text-center col-12 mt-5">
  <a href="{{route('unidadesaude.create')}}" class="btn btn-primary btn-small">
    <b>Nova Unidade de Saúde</b>
  </a>
</div>

<div class="col-12 text-center mt-3">
  <h1>
    Listagem de Unidades
  </h1>
</div>

<table class="table table-bordered shadow" id="unidadeTable">
  <thead>
    <tr class="text-center">
      <th>CNES</th>
      <th>Nome</th>
      <th>Município</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    @foreach ($unidadesaude as $u)
    <tr class="text-center">
      <td>{{$u->cnes}}</td>
      <td>{{strtoupper($u->nome)}}</td>
      <td>{{strtoupper($u->municipio->nome)}}</td>
      <td>
        <div class="dropdown open">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="triggerId" data-toggle="dropdown">
            Selecione
          </button>
          <div class="dropdown-menu" aria-labelledby="triggerId">
            <a class="dropdown-item" href="{{route('unidadesaude.edit', $u->id)}}">Editar</a>
            {{-- <a class="dropdown-item" onclick="return confirm('Confirmar exclusão')" href="{{url('unidadesaude/remove/'.$u->id)}}">Excluir</a> --}}
          </div>
      </td>
      </div>
      </td>
    </tr>
    @endforeach
  </tbody>
</table>
</div>
@endsection