routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/primeiroacesso', 'HomeController@primeiroacesso')->name('primeiroacesso')->middleware('auth');
Route::post('/primeiroacesso', 'HomeController@update')->name('primeiroacesso.update')->middleware('auth');

// ROTAS AUTENTICADAS
Route::middleware(['auth','primeiroacesso'])->group(function () {

    Route::redirect('/', '/home');
    Route::get('/home', 'HomeController@index')->name('home');

    //Usuários
    Route::resource('usuario', 'UserController');

    //Comorbidade
    Route::resource('comorbidade', 'ComorbidadeController');
    Route::get('/comorbidade/remove/{id}', 'ComorbidadeController@delete');

    //Cargos
    Route::resource('cargo', 'CargoController');
    Route::get('/cargo/remove/{id}', 'CargoController@delete');

    //Tipo de serviço
    Route::resource('tipoServico', 'TipoServicoController');
    Route::get('/tipo-servico/remove/{id}', 'TipoServicoController@delete');

    //Unidades de Saúde
    Route::resource('unidadesaude', 'UnidadeSaudeController');
    Route::get('/unidadesaude/remove/{id}', 'UnidadeSaudeController@delete');

    //Pacientes
    Route::resource('paciente', 'PacienteController');
    Route::get('visualizacao/{paciente}','PacienteController@visualizacao')->name('visualizacao');

    //Vínculo
    Route::resource('vinculo', 'VinculoController');
    Route::get('/vinculo/remove/{id}', 'VinculoController@delete');


});

app/TipoServico.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class TipoServico extends Model
{
    protected $table = 'tipo_servico';
}

app/Http/Controllers/TipoServicoController.php
<?php

namespace App\Http\Controllers;

use App\TipoServico;
use Illuminate\Http\Request;
use Request as rq;

class TipoServicoController extends Controller
{
    public function __construct(){
        $this->middleware('verificaperfil:tipo_servicos');
    }
    public function index(){

        $tipoServico = TipoServico::orderBy('descricao')->get();

        return view('tipoServico.index', compact('tipoServico'));
    }

    public function create(){

        $tipoServico = new TipoServico();

        return view('tipoServico.formulario', compact('tipoServico'));
    }

    public function store(Request $request){

        $tipoServico = new TipoServico();
        $tipoServico->descricao = $request->descricao;

        try {
            $save = $tipoServico->save();

            if($save){
                rq::session()->flash('status', 'Tipo de Serviço cadastrado com sucesso.');
            }else{
                rq::session()->flash('status-not', 'Ocorreu um erro ao salvar tipo de serviço.');
            }

        }catch (\Exception $e){
            rq::session()->flash('status-not', 'Ocorreu um erro ao salvar tipo de serviço.'.$e->getMessage());
        }

        return redirect()->route('tipoServico.index');
    }

    public function edit(TipoServico $tipoServico){

        return view('tipoServico.formulario', compact('tipoServico'));
    }

    public function update(Request $request, TipoServico $tipoServico){

        $tipoServico->descricao = $request->descricao;

        try {
            $save = $tipoServico->save();

            if($save){
                rq::session()->flash('status', 'Tipo de serviço atualizado com sucesso.');
            }else{
                rq::session()->flash('status-not', 'Ocorreu um erro ao salvar tipo de serviço.');
            }

        }catch (\Exception $e){
            rq::session()->flash('status-not', 'Ocorreu um erro ao salvar tipo de serviço.'.$e->getMessage());
        }

        return redirect()->route('tipoServico.index');
    }

    public function delete($id)
    {
        $tipoServico = TipoServico::findOrFail($id);

        try{
            $tipoServico->delete();
            rq::session()->flash('status', 'Tipo de serviço '.$tipoServico->descricao.' excluído com sucesso.');
            return redirect()->route('tipoServico.index');
        }
        catch (\Exception $e){

            if($e->getCode() == 23000 ){
                rq::session()->flash('status-not', 'Tipo de Serviço não foi excluído. O mesmo está sendo utilizado em outro cadastro! ');
            }else{
                rq::session()->flash('status-not', 'Tipo de Serviço não foi excluído! '.$e->getMessage());
            }

            return redirect()->route('tipoServico.index');
        }

    }
}

resources/views/tipoServico/formulario.blade.php
@extends('layouts.template')

@section('content')


@include('messages.alert')

@if($tipoServico->exists)

<div class="col-12 text-center">
    <h3>EDITAR TIPO DE SERVIÇO</h3>
</div>

<form action="{{route('tipoServico.update', $tipoServico)}}" method="post">
    <input type="hidden" name="_method" value="put">

    @else

    <div class="col-12 text-center">
        <h3>CADASTRO DE TIPO DE SERVIÇO</h3>
    </div>

    <form action="{{route('tipoServico.store')}}" method="post">
        @endif
        {{ csrf_field() }}
        <div class="row">
            <div class="form-group col-12">
                <label>Nome *</label>
                <input name="descricao" id="descricao" value="{{old('descricao',$tipoServico->descricao)}}" type="text" class="form-control" placeholder="Digite o nome do tipo de serviço" required />
            </div>
        </div>

        <div class="row">
            <div class="form-group form-footer col-12 text-center" style="margin-bottom: 50px">

                <button class="btn btn-primary" type="submit">Salvar</button>

                <a class="btn btn-default" href="{{route('tipoServico.index')}}">
                    Cancelar
                </a>
            </div>
        </div>

    </form>
    @endsection

resources/views/tipoServico/index.blade.php
@extends('layouts.template')

@section('content')

@include('messages.alert')

<div class="text-center col-12 mt-5">
    <a href="{{route('tipoServico.create')}}" class="btn btn-primary btn-small">
        <b>Novo tipo de Serviço</b>
    </a>
</div>

<div class="col-12 text-center mt-3">
    <h1>
        Listagem de Tipos de Serviço
    </h1>
</div>
<table class="table table-bordered shadow col-12" id="tipoServicoTable">
    <thead>
        <tr class="text-center">
            <th>Nome</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($tipoServico as $t)
        <tr class="text-center">
            <td>{{$t->descricao}}</td>

            <th>
                <div class="dropdown open">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="triggerId" data-toggle="dropdown">
                        Selecione
                    </button>
                    <div class="dropdown-menu" aria-labelledby="triggerId">
                        <a class="dropdown-item" href="{{route('tipoServico.edit', $t)}}">Editar</a>
                        <a class="dropdown-item" onclick="return confirm('Confirmar exclusão')" href="{{url('tipo-servico/remove/'.$t->id)}}">Excluir</a>
                    </div>

                </div>
            </th>
        </tr>
        @endforeach
    </tbody>
</table>
</div>

<script>
    $('#tipoServicoTable').DataTable({
        "searching": true,
        "language": {
            "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json"
        }
    });
</script>
@endsection