routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/primeiroacesso', 'HomeController@primeiroacesso')->name('primeiroacesso')->middleware('auth');
Route::post('/primeiroacesso', 'HomeController@update')->name('primeiroacesso.update')->middleware('auth');

// ROTAS AUTENTICADAS
Route::middleware(['auth','primeiroacesso'])->group(function () {

    Route::redirect('/', '/home');
    Route::get('/home', 'HomeController@index')->name('home');

    //Usuários
    Route::resource('usuario', 'UserController');

    //Comorbidade
    Route::resource('comorbidade', 'ComorbidadeController');
    Route::get('/comorbidade/remove/{id}', 'ComorbidadeController@delete');

    //Cargos
    Route::resource('cargo', 'CargoController');
    Route::get('/cargo/remove/{id}', 'CargoController@delete');

    //Tipo de serviço
    Route::resource('tipoServico', 'TipoServicoController');
    Route::get('/tipo-servico/remove/{id}', 'TipoServicoController@delete');

    //Unidades de Saúde
    Route::resource('unidadesaude', 'UnidadeSaudeController');
    Route::get('/unidadesaude/remove/{id}', 'UnidadeSaudeController@delete');

    //Pacientes
    Route::resource('paciente', 'PacienteController');
    Route::get('visualizacao/{paciente}','PacienteController@visualizacao')->name('visualizacao');

    //Vínculo
    Route::resource('vinculo', 'VinculoController');
    Route::get('/vinculo/remove/{id}', 'VinculoController@delete');


});

resources/views/usuarios/create.blade.php
@extends('layouts.template')
@section('content')
    <div class="row justify-content-center">
        <div class="col-12">
            <h1>
                Gerenciamento de usuários
            </h1>
        </div>

        <div class="col-12 col-md-10 my-3">
            <a href="{{route('usuario.index')}}" class="btn btn-danger btn-sm">
                Voltar
            </a>
        </div>

        <div class="col-8 shadow p-3 ">
            <h4>
                Novo usuário
            </h4>
            @if($errors->any())
                <div class="alert alert-danger" role="alert">
                @foreach($errors->all() as $e)
                    <p>{{$e}}</p>
                @endforeach
                </div>
            @endif
            <form action="{{route('usuario.store')}}" method="post" class="form-row">
            @csrf
                <div class="form-group col-4">
                  <label for="">Nome</label>
                  <input type="text" name="nome" id="nome" class="form-control" required>
                </div>
                <div class="form-group col-4">
                  <label for="">Email</label>
                  <input type="email" name="email" id="email" class="form-control" required>
                </div>
                <div class="form-group col-4">
                  <label for="">Unidade de Saúde</label>
                  <select name="unidade" id="unidade" class="form-control" required>
                  @foreach($unidades as $u)
                    <option value="{{$u->id}}">{{$u->nome}}</option>
                  @endforeach
                  </select>
                </div>
                <div class="form-group col-4 offset-4">
                    <div class="form-group">
                      <label for="">Perfil</label>
                      <select class="form-control" name="perfil" id="perfil">
                        @if(auth()->user()->perfil == 1)
                        <option value="2">Administrador de unidade</option>
                        @endif
                        <option value="3">Operador</option>
                      </select>
                    </div>
                </div>
                <div class="col-12 text-center">
                    <button type="submit" class="btn btn-primary">Cadastrar</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/usuarios/edit.blade.php
@extends('layouts.template')
@section('content')
    <div class="row justify-content-center">
        <div class="col-12">
            <h1>
                Gerenciamento de usuários
            </h1>
        </div>

        <div class="col-12 col-md-10 my-3">
            <a href="{{route('usuario.index')}}" class="btn btn-danger btn-sm">
                Voltar
            </a>
        </div>

        <div class="col-8 shadow p-3 ">
            <h4 class="font-weight-bold">
                Novo usuário
            </h4>
            @if($errors->any())
                <div class="alert alert-danger" role="alert">
                @foreach($errors->all() as $e)
                    <p>{{$e}}</p>
                @endforeach
                </div>
            @endif
            <form action="{{route('usuario.update',$user)}}" method="post" class="form-row">
            @csrf
            @method('PUT')
                <div class="form-group col-4">
                  <label class="font-weight-bold">Nome</label>
                  <input type="text" name="name" id="name" class="form-control" value="{{old('name',$user->name)}}" required>
                </div>
                <div class="form-group col-4">
                  <label class="font-weight-bold">Email</label>
                  <input type="email" name="email" id="email" class="form-control" value="{{old('email',$user->email)}}" required>
                </div>
                <div class="form-group col-4">
                  <label class="font-weight-bold">Unidade de Saúde</label>
                  <select name="unidade_id" id="unidade" class="form-control" required>
                  <option value="" disabled>Selecione uma unidade de saúde</option>
                  @foreach($unidades as $u)
                    <option value="{{$u->id}}" {{$u->id == $user->unidade_id?"selected":""}}>
                        {{$u->nome}}
                    </option>
                  @endforeach
                  </select>
                </div>
                <div class="col-12 text-center">
                    <button type="submit" class="btn btn-primary">
                        Salvar
                    </button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/usuarios/index.blade.php
@extends('layouts.template')
@section('content')
    <div class="row justify-content-center">
        <div class="col-12">
            <h1>
                Gerenciamento de usuários
            </h1>
        </div>

        <div class="col-12 text-center my-3">
            <a href="{{route('usuario.create')}}" class="btn btn-primary">
                Novo usuário
            </a>
        </div>
        <div class="col-12 col-md-8">
            @include('messages.error')
        </div>

        <div class="col-12 col-md-8">
            <table class="table table-bordered shadow">
                <thead>
                    <tr class="bg-dark text-white text-center">
                        <th>Nome</th>
                        <th>Email</th>
                        <th>Unidade</th>
                        <th>Perfil</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($users as $u)
                    <tr>
                        <td>{{$u->name}}</td>
                        <td>{{$u->email}}</td>
                        <td>{{$u->unidade->nome}}</td>
                        <td>{{$u->getperfil()}}</td>
                        <td width="10%">
                            <div class="dropdown open">
                                <button class="btn btn-primary dropdown-toggle" type="button" id="triggerId" data-toggle="dropdown">
                                    Selecionar
                                </button>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="{{route('usuario.edit',$u->id)}}">
                                        Editar
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <script>
        $('.table').DataTable({
            "searching": true,
            "language": {
                "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json"
            }
        });
        @if(session('success'))
            alert({{session('success')}});
        @endif
    </script>
@endsection